"""add departments tables

Revision ID: aaaaa0000000
Revises: 6b5f9f8b1a2c
Create Date: 2026-04-17 12:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aaaaa0000000'
down_revision = '6b5f9f8b1a2c'
branch_labels = None
depends_on = None


def _is_pg(conn):
    return conn.dialect.name == "postgresql"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    if _is_pg(conn):
        # PostgreSQL syntax
        # Create departments table
        op.create_table(
            'departments',
            sa.Column('id', sa.String(length=64), primary_key=True),
            sa.Column('tenant_id', sa.String(length=64), nullable=False, index=True),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('parent_id', sa.String(length=64), sa.ForeignKey('departments.id'), nullable=True),
            sa.Column('created_by', sa.String(length=64), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        )
        op.create_index('idx_department_tenant', 'departments', ['tenant_id'])
        op.create_index('idx_department_parent', 'departments', ['parent_id'])

        # Create account_department_joins table
        op.create_table(
            'account_department_joins',
            sa.Column('id', sa.String(length=64), primary_key=True),
            sa.Column('account_id', sa.String(length=64), nullable=False, index=True),
            sa.Column('department_id', sa.String(length=64), sa.ForeignKey('departments.id', ondelete='CASCADE'), nullable=False),
            sa.Column('tenant_id', sa.String(length=64), nullable=False, index=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        )
        op.create_index('idx_account_department_unique', 'account_department_joins', ['account_id', 'department_id'], unique=True)
        op.create_index('idx_join_department', 'account_department_joins', ['department_id'])

        # Create dataset_department_bindings table
        op.create_table(
            'dataset_department_bindings',
            sa.Column('id', sa.String(length=64), primary_key=True),
            sa.Column('dataset_id', sa.String(length=64), nullable=False, index=True),
            sa.Column('department_id', sa.String(length=64), sa.ForeignKey('departments.id', ondelete='CASCADE'), nullable=False),
            sa.Column('tenant_id', sa.String(length=64), nullable=False, index=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        )
        op.create_index('idx_dataset_department_unique', 'dataset_department_bindings', ['dataset_id', 'department_id'], unique=True)
        op.create_index('idx_binding_department', 'dataset_department_bindings', ['department_id'])
    else:
        # MySQL syntax
        op.create_table(
            'departments',
            sa.Column('id', sa.String(length=64), primary_key=True),
            sa.Column('tenant_id', sa.String(length=64), nullable=False, index=True),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('parent_id', sa.String(length=64), sa.ForeignKey('departments.id'), nullable=True),
            sa.Column('created_by', sa.String(length=64), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        )
        op.create_index('idx_department_tenant', 'departments', ['tenant_id'])
        op.create_index('idx_department_parent', 'departments', ['parent_id'])

        op.create_table(
            'account_department_joins',
            sa.Column('id', sa.String(length=64), primary_key=True),
            sa.Column('account_id', sa.String(length=64), nullable=False, index=True),
            sa.Column('department_id', sa.String(length=64), sa.ForeignKey('departments.id', ondelete='CASCADE'), nullable=False),
            sa.Column('tenant_id', sa.String(length=64), nullable=False, index=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        )
        op.create_index('idx_account_department_unique', 'account_department_joins', ['account_id', 'department_id'], unique=True)
        op.create_index('idx_join_department', 'account_department_joins', ['department_id'])

        op.create_table(
            'dataset_department_bindings',
            sa.Column('id', sa.String(length=64), primary_key=True),
            sa.Column('dataset_id', sa.String(length=64), nullable=False, index=True),
            sa.Column('department_id', sa.String(length=64), sa.ForeignKey('departments.id', ondelete='CASCADE'), nullable=False),
            sa.Column('tenant_id', sa.String(length=64), nullable=False, index=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        )
        op.create_index('idx_dataset_department_unique', 'dataset_department_bindings', ['dataset_id', 'department_id'], unique=True)
        op.create_index('idx_binding_department', 'dataset_department_bindings', ['department_id'])

    # Add columns to datasets table for personal/department knowledge base
    if _is_pg(conn):
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_personal', sa.Boolean(), server_default=sa.text('false'), nullable=False))
            batch_op.add_column(sa.Column('department_id', sa.String(length=64), nullable=True))
    else:
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_personal', sa.Boolean(), server_default='0', nullable=False))
            batch_op.add_column(sa.Column('department_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    if _is_pg(conn):
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.drop_column('department_id')
            batch_op.drop_column('is_personal')
    else:
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.drop_column('department_id')
            batch_op.drop_column('is_personal')

    op.drop_index('idx_binding_department', table_name='dataset_department_bindings')
    op.drop_index('idx_dataset_department_unique', table_name='dataset_department_bindings')
    op.drop_table('dataset_department_bindings')

    op.drop_index('idx_join_department', table_name='account_department_joins')
    op.drop_index('idx_account_department_unique', table_name='account_department_joins')
    op.drop_table('account_department_joins')

    op.drop_index('idx_department_parent', table_name='departments')
    op.drop_index('idx_department_tenant', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
